#!/usr/bin/env python3
"""Render findings.json as a PR comment and upsert it (edit-in-place).

Finds a prior vulngate comment by a hidden marker and PATCHes it, so pushing
new commits updates one comment instead of spamming a new one each time.
Pure stdlib (urllib) — no dependencies. Best-effort: never fails the build.

Env: GITHUB_TOKEN, GITHUB_REPOSITORY (owner/repo), GITHUB_EVENT_PATH.
Arg:  path to findings.json (default: findings.json).
"""

from __future__ import annotations

import json
import os
import sys
import urllib.error
import urllib.request
from pathlib import Path

MARKER = "<!-- vulngate-report -->"
SEVERITIES = ("critical", "high", "medium", "low")
EMOJI = {"critical": "🟣", "high": "🔴", "medium": "🟡", "low": "🔵"}
DEP = ("pip-audit", "npm-audit")
API = "https://api.github.com"


# ── markdown rendering (pure, testable) ──────────────────────────────────────
def render_markdown(data: dict) -> str:
    scan, summary = data["scan"], data["summary"]
    findings = data["findings"]
    ec = scan["exit_code"]
    verdict = ("✅ **Passed**" if ec == 0 else
               "❌ **Failed**" if ec == 1 else "⚠️ **Tool error**")

    out = [MARKER, "## vulngate security report", ""]
    out.append(f"{verdict} — threshold `{scan['fail_on']}`, {summary['total']} finding(s)")
    out.append("")
    counts = " · ".join(f"{EMOJI[s]} {summary[s]} {s}" for s in SEVERITIES if summary[s]) or "none"
    out.append(f"**Severity:** {counts}")

    scanners = ", ".join(
        f"`{s['name']}`" + ("" if s["status"] == "completed" else f" ({s['status']})")
        for s in scan["scanners"]
    )
    out.append(f"**Scanners:** {scanners}")
    if any(s.get("triage") for s in findings):
        out.append("**LLM triage:** on (explanations and suggested fixes included)")
    out.append("")

    if not findings:
        out.append("No findings at or above the threshold. 🎉")
        return "\n".join(out)

    # Code findings individually; dependency findings grouped per package.
    code = [f for f in findings if f["scanner"] not in DEP]
    deps: dict[tuple, list] = {}
    for f in findings:
        if f["scanner"] in DEP:
            deps.setdefault((f["scanner"], f["file"], (f["details"] or {}).get("package", "?")), []).append(f)

    if code:
        out.append("<details open><summary><b>Code findings</b></summary>\n")
        for f in sorted(code, key=lambda x: SEVERITIES.index(x["severity"])):
            loc = f["file"] + (f":{f['line']}" if f.get("line") else "")
            out.append(f"- {EMOJI[f['severity']]} **{f['severity'].upper()}** `{loc}` — {f['plain_summary']}")
            out.append(f"  - _{f['scanner']}_ · `{f['rule']}` · fix: {f['remediation_hint']}")
            t = f.get("triage")
            if t:
                fp = " · ⚠️ likely false positive" if t.get("false_positive") else ""
                out.append(f"  - 🤖 {t.get('explanation','').strip()}{fp}")
                if t.get("suggested_fix"):
                    out.append(f"  - 🤖 suggested fix: {t['suggested_fix'].strip()}")
        out.append("\n</details>")

    if deps:
        out.append("\n<details><summary><b>Dependency findings</b></summary>\n")
        for (scanner, file, pkg), fs in sorted(deps.items(), key=lambda kv: SEVERITIES.index(min((x["severity"] for x in kv[1]), key=SEVERITIES.index))):
            sev = min((x["severity"] for x in fs), key=SEVERITIES.index)
            out.append(f"- {EMOJI[sev]} **{sev.upper()}** `{pkg}` — {len(fs)} advisor{'y' if len(fs)==1 else 'ies'} in `{file}` (_{scanner}_)")
        out.append("\n</details>")

    out.append(f"\n<sub>Generated by [vulngate](https://github.com/cisoventures/vulngate) · we scan the code, not the agents.</sub>")
    return "\n".join(out)


# ── GitHub API (stdlib) ──────────────────────────────────────────────────────
def _api(method: str, url: str, token: str, body: dict | None = None):
    data = json.dumps(body).encode() if body is not None else None
    req = urllib.request.Request(url, data=data, method=method, headers={
        "Authorization": f"Bearer {token}",
        "Accept": "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28",
        "Content-Type": "application/json",
        "User-Agent": "vulngate",
    })
    with urllib.request.urlopen(req, timeout=30) as r:
        return json.loads(r.read() or "null")


def _pr_number(event_path: str | None) -> int | None:
    if not event_path or not Path(event_path).exists():
        return None
    try:
        ev = json.loads(Path(event_path).read_text())
    except (json.JSONDecodeError, OSError):
        return None
    return (ev.get("pull_request") or {}).get("number") or ev.get("number")


def main() -> int:
    path = sys.argv[1] if len(sys.argv) > 1 else "findings.json"
    token = os.environ.get("GITHUB_TOKEN")
    repo = os.environ.get("GITHUB_REPOSITORY", "")
    pr = _pr_number(os.environ.get("GITHUB_EVENT_PATH"))
    if not (token and repo and pr):
        print("pr_comment: not a PR context (or missing token/repo); skipping")
        return 0
    try:
        data = json.loads(Path(path).read_text())
    except (json.JSONDecodeError, OSError) as e:
        print(f"pr_comment: cannot read {path}: {e}", file=sys.stderr)
        return 0

    body = render_markdown(data)
    try:
        comments = _api("GET", f"{API}/repos/{repo}/issues/{pr}/comments?per_page=100", token) or []
        existing = next((c for c in comments if MARKER in (c.get("body") or "")), None)
        if existing:
            _api("PATCH", f"{API}/repos/{repo}/issues/comments/{existing['id']}", token, {"body": body})
            print(f"pr_comment: updated comment {existing['id']}")
        else:
            _api("POST", f"{API}/repos/{repo}/issues/{pr}/comments", token, {"body": body})
            print("pr_comment: created comment")
    except (urllib.error.URLError, urllib.error.HTTPError) as e:
        print(f"pr_comment: GitHub API error (skipping): {e}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
